import { Inter } from 'next/font/google'
import { NavBar } from '@/components/NavBar'
import { Layout } from '@/components/Layout'
import { TaskProvider } from '@/context/TaskContext'
import { Toaster } from 'react-hot-toast'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TaskProvider>
          <NavBar />
          <Layout>
            {children}
          </Layout>
          <Toaster/>
        </TaskProvider>
      </body>
    </html>
  );
}
